[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --themesDir ../.."

[build.environment]
  HUGO_VERSION = "0.81.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "https://uswds-hugo-theme.netlify.app"
